---
title: "CDS 101 Final Project"
author: "Group 4"
date: "`r Sys.Date()`"
output: pdf_document
---
## Set up - Naeun
```{r set up, include=FALSE}
#
rm(list = ls())

suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(ggmosaic))
suppressPackageStartupMessages(library(modelr))
suppressPackageStartupMessages(library(boot))
suppressPackageStartupMessages(library(infer))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(caTools))

# 
AgeDataset <- read_csv("AgeDataset-V1.csv")
```

## Tyding the dataset - Naeun
```{r}
#rename the variable
AgeDataset <- AgeDataset %>%
  rename(
    birth_year= `Birth year`,
    death_year = `Death year`,
    manner_of_death = `Manner of death`,
    age_of_death = `Age of death`
  )

# Set seed for reproducibility
head(AgeDataset)

# Check data types
str(AgeDataset)

# Set seed for reproducibility
set.seed(123)

# Split the data
split <- sample.split(AgeDataset$contains_four, SplitRatio = 0.7)

# Create training and testing sets
training_set <- subset(AgeDataset, split == TRUE)
testing_set <- subset(AgeDataset, split == FALSE)

# Display the number of observations in each set
cat("Number of observations in the training set:", nrow(training_set), "\n")
cat("Number of observations in the testing set:", nrow(testing_set), "\n")
```

* we need more here

## Null/Alternative Hypothesis - Gahyun
```{r}
women_data <- AgeDataset %>%
  filter(Gender == 'Female')
```
```{r}
women_data <- women_data %>%
  mutate(contains_4 = str_detect(as.character(birth_year), "4"))
```
```{r}
set.seed(123)
null_distribution <- women_data %>%
  specify(response = age_of_death, explanatory = contains_4) %>%
  hypothesize(null = "independence") %>%
  generate(reps = 1000, type = "permute") %>% 
  calculate(stat = "diff in means", order = c(TRUE, FALSE))
```
```{r}
observed_diff <- women_data %>%
  specify(response = age_of_death, explanatory = contains_4) %>%
  calculate(stat = "diff in means", order = c(TRUE, FALSE))
```
```{r}
p_value <- null_distribution %>%
  get_p_value(obs_stat = observed_diff, direction = "both")

null_distribution %>%
  visualize() +
  shade_p_value(obs_stat = observed_diff, direction = "both") +
  labs(title = "Simulation Based Null Distribution",
       x = "Difference in Means",
       y = "Count")
```

##Logistic regression modeling - Shin & Jinuk
```{r}
#grouping to group 4 vs group 0
AgeDataset <- AgeDataset %>%
  mutate(contains_four = ifelse(grepl("4", as.character(birth_year)), 1, 0))

AgeDataset <- AgeDataset %>%
  mutate(contains_super = as.logical(contains_four)
  )
```
```{r}
AgeDataset <- AgeDataset %>%
  filter(birth_year > 0)
```

```{r}
#col_types=...
#as.logistic (true/false)
```
### percentage graph
```{r}
AgeDataset %>% 
  pivot_longer(cols = age_of_death|birth_year,
               names_to = "info1",
               values_to = "value1") %>% 
  ggplot() +
  geom_histogram(
    mapping = aes(
      x = value1,
      y = after_stat(count) / sum(after_stat(count)) * 100,
      fill = contains_super
    ),
    position = "identity",
    alpha = 0.6
  ) +
  facet_wrap(~info1, scales = "free") +
  labs(
    x = "value",
    y = "frequency",
    title = "Histogram of survival due to age of death and birth year"
  )
```
### tidied graph
```{r}
AgeDataset %>% 
  pivot_longer(cols = age_of_death|birth_year,
               names_to = "info1",
               values_to = "value1") %>% 
  ggplot() +
  geom_histogram(
    mapping = aes(
      x = value1,
      fill = contains_super
    ),
    position = "identity",
    alpha = 0.6,
    bins = 30
  ) +
  facet_wrap(~info1, scales = "free") +
  labs(
    x = "value",
    y = "frequency",
    title = "Histogram of survival due to age of death and birth year"
  )
```
```{r}
top_occupations <- AgeDataset %>%
  count(Occupation) %>%
  top_n(15, wt = n) %>%
  pull(Occupation)

filtered_data <- AgeDataset %>%
  filter(Occupation %in% top_occupations)

# Pivot the dataset and plot
filtered_data %>%
  pivot_longer(cols = c(Country, Occupation, Gender), names_to = "info2", values_to = "value2") %>%
  ggplot() +
  geom_bar(mapping = aes(x = value2, fill = contains_super), alpha = 0.6) +
  facet_wrap(~info2, scales = "free") +
  labs(
    x = "value", 
    y = "frequency", 
    title = "Bar graph of survivors by passenger info"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
```{r}
AgeDataset <- AgeDataset %>% 
  filter(!is.na(Gender) & !is.na(age_of_death) & !is.na(contains_super))
print("1")

# Convert necessary columns to factors
AgeDataset <- AgeDataset %>%
  mutate(Gender = as.factor(Gender),
         contains_super = as.factor(contains_super))

# Create the mosaic plot
AgeDataset %>% 
  ggplot() +
  geom_mosaic(aes(weight = age_of_death, x = product(Gender), fill = Gender)) +
  facet_grid(. ~ contains_super, scales = "free") +
  labs(x = "Gender", 
       y = "Count", 
       title = "Mosaic Plot of superstitioon") +
  theme_minimal()
```

```{r}
model_1 <- glm(contains_super ~ age_of_death, data = AgeDataset, family = "binomial")
```
```{r}
model_1_preds <-  AgeDataset %>% 
  add_predictions(model_1, type = "response") %>% 
  mutate(
    outcome = if_else(condition = pred > 0.5,
                      true = 1,
                      false = 0)
  )

model_1_preds %>% 
  mutate(
    correct = if_else(
      condition = contains_four == outcome,
      true = 1,
      false = 0
    )
  ) %>% 
  summarize(
    total_correct = sum(correct),
    accuracy = total_correct/n()
  )
```

